---
- name: ensure prometheus data directory owner is nobody
  #become: yes
  file:
        path: "{{ prometheus_volume_source}}"
        owner: root
        group: root
        mode: 0777 
        state: directory 
  notify: 
    - Restart prometheus container


- name: get host's external IP address
  # See http://www.commandlinefu.com/commands/view/5427/get-your-external-ip-address
  # for alternatives to this command
  command: curl --silent --fail http://ifconfig.me/ip
  register: host_external_ip

- set_fact: external_ip_address="{{host_external_ip.stdout}}"

- name: Copy config file
  #become: yes
  template:
        src: prometheus.yml.j2
        dest: "{{ prometheus_volume_source}}/prometheus.yml"
        owner: root
        mode: 0666 
  notify: 
    - Restart prometheus container

- name: Copy rule file
  #become: yes
  copy:
    src: "{{ prometheus_rule_file_name }}"
    dest: "{{ prometheus_volume_source }}/{{ prometheus_rule_file_name }}"
    owner: root
    mode: 0666
  notify: 
    - Restart prometheus container


- name: Start prometheus container
  docker_container:
    name: "{{ prometheus_container_name }}"
    hostname: "{{ prometheus_container_name }}"
    image: "{{ prometheus_image }}"
    command: "{% for key in prometheus_commandline_args %}--{{key}}={{prometheus_commandline_args[key]}} {% endfor %}"
    published_ports:
      - 9090:9090
    volumes:
      - "{{ prometheus_volume_mountinstruction }}" 
    restart_policy: always