---
galaxy_info:
  author: Valentin Gostev
  description: Ansible role deploys Grafana Loki container
  role_name: ct_grafana_loki
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - grafana
    - loki
    - logs
    - logging
    - syslog
allow_duplicates: false
dependencies: []
...
