- name: Prepare host
  hosts: hippy_server
  become: yes
  become_user: root
  vars:
    pip_install_packages:
      - name: docker

  roles:
    - init_prepare
    - geerlingguy.pip
    - geerlingguy.docker
